### ISSUE TITLE
MIgration et seed problem

### ISSUE THREAD

**Issue by ismaeljoseph** [redgluten/polenta#1]
All tables seems not migrate,
and all table create are empty

I'm sorry that's the first time i'm sending issue

**Comment by redgluten** [comment]
Can you detail which tables are not migrated? I’ll try to add old migrations to ensure all of them are present if I can.

Concerning the seeding I may complete the database seeding process to provide a full seeding for other people to fork the project more easily but you should really make your own seeding or manually add the content to better reflect your project. I encourage you to have a look at the [documentation on seeding](https://laravel.com/docs/5.3/seeding) to do so. If there are some table seeding necessary to get started (such as users maybe?) that are not documented please let me know.

You can also use [tinker](https://scotch.io/tutorials/tinker-with-the-data-in-your-laravel-apps-with-php-artisan-tinker) to add some content in your database, that’s what I usually do for basic users:

``` bash
php artisan tinker
> $user = App\User::create(['email' => 'email@exemple.org', 'password' => bcrypt('password')];
```

**Comment by ismaeljoseph** [comment]
Thank you everything work fine now. Think you for sharing your project.
